### ISSUE TITLE
Does two finger scrolling work just like on Macbook?

### ISSUE THREAD

**Issue by Meai1** [iberianpig/xSwipe#16]
Hi, I am wondering if when I buy a magic trackpad if it's going to work with two finger scrolling and single finger click, in Eclipse, Browser, gedit.. basically in all applications without having to do anything special about it.
Is that something you use? Or do you just use xSwipe for touchscreens in general?

**Comment by Fallon9111** [comment]
On my macbook pro (8,1) the two finger scrolling, single finger click and two finger right click, on most distros, works srtaight out of the box (needs xf86-input-synaptics) and there is no need for xSwipe.

 I have previously used a bluetooth magic trackpad and whilst it works great when used for one distro, it is a real pain to configure to use automatically between two distros or especially between os x/linux. If this is what you plan on doing you may need to setup bluetooth on every reboot! If you are only going to use on distro, then once configured it will run great (1/2 click and scrolling works great)

 If you want more than two finger touch (such as four finger swipe or three finger swipe), then you will absolutely need additional software such as xSwipe. A great guide on configuring the trackpad (without additional software) to best suit you can be found on the Arch Wiki (https://wiki.archlinux.org/index.php/Touchpad_Synaptics). Otherwise if you require xSwipe just follow the instructions on github :)

**Comment by Meai1** [comment]
Sorry what i meant: i plan to buy a magick trackpad and use it on my ubuntu pc. Does that szenario work or do you have experience with that?  So i dont have a mac at all in this scenario

**Comment by Fallon9111** [comment]
I haven't personally tried connecting an apple trackpad to a non-apple hardware, but I have connected it successfully to linux, as detailed further above. AFAIK it should work fine with any computer (assuming you have working bluetooth). If te trackpad doesn't work with your computer then just send it back to apple and get a refund.
